version: '3.3'

services:
  app:
    build: ..
    env_file: .env
    extra_hosts:
      - "notify-contest.ddns.net:192.168.31.200"
  nginx:
    image: docker.io/bitnami/nginx:1.21
    ports:
      - '443:8443'
    volumes:
      - ./nginx/conf-build/nginx.conf:/opt/bitnami/nginx/conf/nginx.conf
      - ./nginx/ssl:/opt/bitnami/nginx/ssl
    restart: unless-stopped
  redis:
    ports:
      - '6379:6379'
  postgresql:
    ports:
      - '5432:5432'
  rabbitmq:
    ports:
      - '5672:5672'
      - '15672:15672'
      - '15692:15692'
  grafana:
    ports:
      - '3000:3000'
