version: "3"

services:
  i4ins:
    build:
      context: .
    container_name: i4ins
    image: i4ins
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/ftns
      - KAFKA_USERNAME=<USERNAME>
      - KAFKA_PASSWORD=<PASSWORD>
      - KAFKA_BROKER=notification.services.tonlabs.io:29092
    volumes:
      - ./logs:/logs
    networks:
      - ftns-network
    ports:
      - 3000:3000
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:5.0
    volumes:
      - ./data:/data/db
    networks:
      - ftns-network
    hostname: mongo
    ports:
      - '27017:27017'

networks:
  ftns-network:
    driver: bridge
