apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  strategy: 
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      imagePullSecrets:
        - name: regsecret
      containers:
      - image: {{ .Values.werf.image.freetonnotificationservice }}
        name: app
        resources:
          requests:
            memory: "50Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: KAFKA_PASSWORD
            value: {{ .Values.app.kafka_password | quote }}
        volumeMounts:
        - mountPath: /app/databases
          name: volume    
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: databases-volume-claim
